# Generated by Django 4.1.1 on 2022-11-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=20)),
                ('customer', models.CharField(max_length=30)),
                ('bl', models.CharField(max_length=20)),
                ('pic', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('trc', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('etc', models.TextField(max_length=256)),
            ],
        ),
    ]
